-- Tabela de auditoria para alterações de configurações e permissões
-- Executar no Supabase SQL Editor
begin;

create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    action text not null,
    setting_key text,
    old_value text,
    new_value text,
    changed_by_id text,
    changed_by_name text,
    changed_by_username text,
    created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_at_idx
    on public.audit_logs (created_at desc);

create index if not exists audit_logs_action_idx
    on public.audit_logs (action, created_at desc);

alter table public.audit_logs enable row level security;

revoke all privileges on table public.audit_logs from anon, authenticated;
grant select, insert on table public.audit_logs to service_role;
grant usage, select on sequence public.audit_logs_id_seq to service_role;

-- Garante configuração inicial caso não exista
insert into public.settings (key, value)
values ('hide_client_phone_from_collaborators', 'false')
on conflict (key) do nothing;

commit;
