-- Review in a staging project first, then run in Supabase SQL Editor.
-- The application accesses these tables only through its protected backend.
begin;

alter table public.professionals alter column password type text;

create unique index if not exists professionals_username_ci_unique
    on public.professionals (lower(username));

create index if not exists appointments_professional_date_idx
    on public.appointments (professional_id, date, time);

create index if not exists appointments_client_phone_idx
    on public.appointments (client_phone, date);

create index if not exists notifications_created_at_idx
    on public.notifications (created_at desc);

-- One-time client login codes. Neither the WhatsApp number nor the six-digit
-- code is stored here: both values are keyed hashes generated by the backend.
create table if not exists public.client_login_codes (
    id bigint generated by default as identity primary key,
    client_id text,
    phone_hash text not null check (length(phone_hash) >= 40),
    code_hash text not null check (length(code_hash) >= 40),
    expires_at timestamptz not null,
    attempts smallint not null default 0 check (attempts >= 0),
    max_attempts smallint not null default 5 check (max_attempts between 1 and 10),
    last_sent_at timestamptz not null default now(),
    consumed_at timestamptz,
    created_at timestamptz not null default now()
);

create unique index if not exists client_login_codes_one_active_phone
    on public.client_login_codes (phone_hash)
    where consumed_at is null;

create index if not exists client_login_codes_expiry_idx
    on public.client_login_codes (expires_at);

create index if not exists client_login_codes_phone_created_idx
    on public.client_login_codes (phone_hash, created_at desc);

alter table public.professionals enable row level security;
alter table public.clients enable row level security;
alter table public.services enable row level security;
alter table public.appointments enable row level security;
alter table public.settings enable row level security;
alter table public.notifications enable row level security;
alter table public.client_login_codes enable row level security;

revoke all privileges on table public.professionals from anon, authenticated;
revoke all privileges on table public.clients from anon, authenticated;
revoke all privileges on table public.services from anon, authenticated;
revoke all privileges on table public.appointments from anon, authenticated;
revoke all privileges on table public.settings from anon, authenticated;
revoke all privileges on table public.notifications from anon, authenticated;
revoke all privileges on table public.client_login_codes from anon, authenticated;
grant select, insert, update, delete on table public.client_login_codes to service_role;
grant usage, select on sequence public.client_login_codes_id_seq to service_role;

-- Atomically checks one code, increments failed attempts and consumes successful
-- or exhausted challenges. Keeping this in one locked transaction prevents two
-- simultaneous verification requests from reusing the same code.
create or replace function public.consume_client_login_code(
    p_phone_hash text,
    p_code_hash text,
    p_now timestamptz
)
returns table(status text, client_id text)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    current_code public.client_login_codes%rowtype;
    next_attempts smallint;
begin
    select challenge.*
      into current_code
      from public.client_login_codes as challenge
     where challenge.phone_hash = p_phone_hash
       and challenge.consumed_at is null
     order by challenge.created_at desc
     limit 1
       for update;

    if not found then
        return query select 'invalid'::text, null::text;
        return;
    end if;

    if current_code.expires_at <= p_now then
        update public.client_login_codes
           set consumed_at = p_now
         where id = current_code.id;
        return query select 'expired'::text, null::text;
        return;
    end if;

    if current_code.attempts >= current_code.max_attempts then
        update public.client_login_codes
           set consumed_at = coalesce(consumed_at, p_now)
         where id = current_code.id;
        return query select 'too_many_attempts'::text, null::text;
        return;
    end if;

    if current_code.code_hash <> p_code_hash then
        next_attempts := current_code.attempts + 1;
        update public.client_login_codes
           set attempts = next_attempts,
               consumed_at = case when next_attempts >= max_attempts then p_now else consumed_at end
         where id = current_code.id;

        if next_attempts >= current_code.max_attempts then
            return query select 'too_many_attempts'::text, null::text;
        else
            return query select 'invalid'::text, null::text;
        end if;
        return;
    end if;

    update public.client_login_codes
       set consumed_at = p_now
     where id = current_code.id;
    return query select 'verified'::text, current_code.client_id;
end;
$$;

revoke all on function public.consume_client_login_code(text, text, timestamptz) from public, anon, authenticated;
grant execute on function public.consume_client_login_code(text, text, timestamptz) to service_role;

-- Prevent two active appointments from starting in the same slot. The backend
-- also checks overlaps involving longer and multi-service appointments.
create unique index if not exists appointments_unique_active_start
    on public.appointments (professional_id, date, time)
    where status <> 'cancelado';

commit;
