-- Non-destructive development migration.
-- Canonical contract for refresh_tokens + per-day schedule in settings.
-- Safe to re-run. Does not drop work_start / work_end / work_days.
begin;

-- ---------------------------------------------------------------------------
-- JWT claim helpers. Used by authenticated policies only.
-- Backend uses service_role (BYPASSRLS); these policies are defense in depth.
-- ---------------------------------------------------------------------------
create or replace function public.app_jwt_claims()
returns jsonb
language sql
stable
security invoker
set search_path = pg_catalog, public, pg_temp
as $$
    select coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb, '{}'::jsonb);
$$;

create or replace function public.app_user_id()
returns text
language sql
stable
security invoker
set search_path = pg_catalog, public, pg_temp
as $$
    select coalesce(
        nullif(public.app_jwt_claims() ->> 'app_user_id', ''),
        nullif(public.app_jwt_claims() ->> 'user_id', '')
    );
$$;

create or replace function public.app_user_type()
returns text
language sql
stable
security invoker
set search_path = pg_catalog, public, pg_temp
as $$
    select coalesce(
        nullif(public.app_jwt_claims() ->> 'app_user_type', ''),
        nullif(public.app_jwt_claims() ->> 'user_type', '')
    );
$$;

create or replace function public.app_is_privileged_staff()
returns boolean
language sql
stable
security invoker
set search_path = pg_catalog, public, pg_temp
as $$
    select
        coalesce(public.app_jwt_claims() ->> 'app_user_type', public.app_jwt_claims() ->> 'user_type', '') = 'staff'
        and (
            coalesce(public.app_jwt_claims() ->> 'app_role', public.app_jwt_claims() ->> 'staff_role', '') in ('admin', 'owner')
            or coalesce(public.app_jwt_claims() ->> 'app_is_owner', '') in ('true', 't', '1')
        );
$$;

revoke all on function public.app_jwt_claims() from public, anon;
revoke all on function public.app_user_id() from public, anon;
revoke all on function public.app_user_type() from public, anon;
revoke all on function public.app_is_privileged_staff() from public, anon;
grant execute on function public.app_jwt_claims() to authenticated, service_role;
grant execute on function public.app_user_id() to authenticated, service_role;
grant execute on function public.app_user_type() to authenticated, service_role;
grant execute on function public.app_is_privileged_staff() to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- refresh_tokens
-- user_id is TEXT on purpose: persist String(professionals.id) / String(clients.id).
-- professionals.id / clients.id in this project are numeric (int/bigint), not uuid.
-- ---------------------------------------------------------------------------
create table if not exists public.refresh_tokens (
    id bigint generated by default as identity primary key,
    user_id text not null check (length(btrim(user_id)) > 0),
    user_type text not null check (user_type in ('staff', 'client')),
    token_hash text not null check (length(token_hash) >= 40),
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    revoked_at timestamptz,
    replaced_by_token_id bigint,
    constraint refresh_tokens_revoked_after_created
        check (revoked_at is null or revoked_at >= created_at)
);

alter table public.refresh_tokens
    add column if not exists replaced_by_token_id bigint;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'refresh_tokens_replaced_by_token_id_fkey'
    ) then
        alter table public.refresh_tokens
            add constraint refresh_tokens_replaced_by_token_id_fkey
            foreign key (replaced_by_token_id)
            references public.refresh_tokens(id)
            on delete set null;
    end if;
end
$$;

comment on table public.refresh_tokens is
    'Hashed refresh sessions. Store only a digest, never the raw token. App TTL: staff access 8h, refresh 30d.';
comment on column public.refresh_tokens.user_id is
    'Application subject id as text: String(professionals.id) or String(clients.id).';
comment on column public.refresh_tokens.user_type is
    'staff | client.';
comment on column public.refresh_tokens.token_hash is
    'SHA-256 digest (hex or base64url, min 40 chars).';
comment on column public.refresh_tokens.expires_at is
    'Absolute expiry of this refresh row.';
comment on column public.refresh_tokens.revoked_at is
    'Set on logout/rotation/reuse. SELECT is allowed on revoked rows (reuse detection).';
comment on column public.refresh_tokens.replaced_by_token_id is
    'Next token in a rotation chain. Null if this row was not replaced.';

create unique index if not exists refresh_tokens_token_hash_uidx
    on public.refresh_tokens (token_hash);

create index if not exists refresh_tokens_user_id_idx
    on public.refresh_tokens (user_id);

create index if not exists idx_refresh_tokens_user
    on public.refresh_tokens (user_id, user_type);

create index if not exists idx_refresh_tokens_expires
    on public.refresh_tokens (expires_at);

create index if not exists refresh_tokens_expires_at_idx
    on public.refresh_tokens (expires_at);

create index if not exists idx_refresh_tokens_revoked
    on public.refresh_tokens (revoked_at)
    where revoked_at is not null;

create index if not exists idx_refresh_tokens_replaced_by
    on public.refresh_tokens (replaced_by_token_id);

create index if not exists refresh_tokens_user_active_idx
    on public.refresh_tokens (user_id, user_type, expires_at)
    where revoked_at is null;

alter table public.refresh_tokens enable row level security;
alter table public.refresh_tokens force row level security;

drop policy if exists "Users can view own refresh tokens" on public.refresh_tokens;
drop policy if exists "Admins can view all staff refresh tokens" on public.refresh_tokens;
drop policy if exists "Service role full access" on public.refresh_tokens;
drop policy if exists refresh_tokens_select_own_or_admin on public.refresh_tokens;
drop policy if exists refresh_tokens_insert_own_or_admin on public.refresh_tokens;
drop policy if exists refresh_tokens_update_own_or_admin on public.refresh_tokens;
drop policy if exists refresh_tokens_delete_admin_only on public.refresh_tokens;

-- Own rows, including revoked (needed for reuse detection).
create policy "Users can view own refresh tokens"
    on public.refresh_tokens
    for select
    to authenticated
    using (
        coalesce(public.app_user_id(), '') <> ''
        and coalesce(public.app_user_type(), '') <> ''
        and user_id = public.app_user_id()
        and user_type = public.app_user_type()
    );

create policy "Admins can view all staff refresh tokens"
    on public.refresh_tokens
    for select
    to authenticated
    using (public.app_is_privileged_staff());

-- Named policy the backend asked about. Covers SELECT/INSERT/UPDATE/DELETE.
-- Hosted Supabase service_role also has BYPASSRLS, so this is belt-and-suspenders
-- together with the GRANT below. No extra policy is required for revoked rows
-- or replaced_by_token_id: those are ordinary columns, not filtered.
create policy "Service role full access"
    on public.refresh_tokens
    for all
    to service_role
    using (true)
    with check (true);

revoke all privileges on table public.refresh_tokens from public, anon, authenticated;
grant select, insert, update, delete on table public.refresh_tokens to service_role;
do $$
begin
    if exists (
        select 1 from pg_class c
        join pg_namespace n on n.oid = c.relnamespace
        where n.nspname = 'public' and c.relname = 'refresh_tokens_id_seq' and c.relkind = 'S'
    ) then
        execute 'grant usage, select on sequence public.refresh_tokens_id_seq to service_role';
    end if;
end
$$;

-- ---------------------------------------------------------------------------
-- Per-day schedule lives in settings.value (TEXT). No new column.
-- Canonical keys:
--   schedule
--   professional_<numeric-id>_schedule
-- JSON: {"dom": null, "seg": {"start":"09:00","end":"18:00"}, ...}
-- Legacy keys work_start / work_end / work_days are kept as fallback.
-- ---------------------------------------------------------------------------
create or replace function public.is_hhmm(p_value text)
returns boolean
language sql
immutable
security invoker
set search_path = pg_catalog, public, pg_temp
as $$
    select p_value ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$';
$$;

create or replace function public.is_valid_work_hours_by_day(p_value jsonb)
returns boolean
language plpgsql
immutable
security invoker
set search_path = pg_catalog, public, pg_temp
as $$
declare
    day_key text;
    slot jsonb;
    start_txt text;
    end_txt text;
begin
    if p_value is null or jsonb_typeof(p_value) <> 'object' then
        return false;
    end if;

    if (
        select coalesce(array_agg(key order by key), '{}')
        from jsonb_object_keys(p_value) as key
    ) is distinct from array['dom','qua','qui','sab','seg','sex','ter'] then
        return false;
    end if;

    foreach day_key in array array['dom','seg','ter','qua','qui','sex','sab']
    loop
        slot := p_value -> day_key;
        if slot is null or slot = 'null'::jsonb then
            continue;
        end if;
        if jsonb_typeof(slot) <> 'object' then
            return false;
        end if;
        if (
            select coalesce(array_agg(key order by key), '{}')
            from jsonb_object_keys(slot) as key
        ) is distinct from array['end','start'] then
            return false;
        end if;
        start_txt := slot ->> 'start';
        end_txt := slot ->> 'end';
        if not public.is_hhmm(start_txt) or not public.is_hhmm(end_txt) then
            return false;
        end if;
        if start_txt::time >= end_txt::time then
            return false;
        end if;
    end loop;

    return true;
end;
$$;

create or replace function public.build_work_hours_by_day(
    p_work_days text,
    p_work_start text,
    p_work_end text
)
returns jsonb
language plpgsql
immutable
security invoker
set search_path = pg_catalog, public, pg_temp
as $$
declare
    days jsonb := '[]'::jsonb;
    start_txt text := coalesce(nullif(btrim(p_work_start), ''), '09:00');
    end_txt text := coalesce(nullif(btrim(p_work_end), ''), '20:00');
    result jsonb := '{}'::jsonb;
    day_key text;
    open_days text[] := '{}';
begin
    if not public.is_hhmm(start_txt) then
        start_txt := '09:00';
    end if;
    if not public.is_hhmm(end_txt) then
        end_txt := '20:00';
    end if;
    if start_txt::time >= end_txt::time then
        start_txt := '09:00';
        end_txt := '20:00';
    end if;

    begin
        days := coalesce(p_work_days::jsonb, '[]'::jsonb);
    exception when others then
        days := '[]'::jsonb;
    end;

    if jsonb_typeof(days) = 'array' then
        select coalesce(array_agg(value), '{}')
          into open_days
          from jsonb_array_elements_text(days) as value
         where value in ('dom','seg','ter','qua','qui','sex','sab');
    end if;

    if coalesce(array_length(open_days, 1), 0) = 0 then
        open_days := array['seg','ter','qua','qui','sex','sab'];
    end if;

    foreach day_key in array array['dom','seg','ter','qua','qui','sex','sab']
    loop
        if day_key = any(open_days) then
            result := result || jsonb_build_object(
                day_key,
                jsonb_build_object('start', start_txt, 'end', end_txt)
            );
        else
            result := result || jsonb_build_object(day_key, 'null'::jsonb);
        end if;
    end loop;

    return result;
end;
$$;

create or replace function public.settings_guard_work_hours_by_day()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public, pg_temp
as $$
begin
    if new.key is null then
        return new;
    end if;
    if new.key in ('schedule', 'work_hours_by_day')
       or new.key ~ '^professional_[0-9]+_(schedule|work_hours_by_day)$' then
        if not public.is_valid_work_hours_by_day(new.value::jsonb) then
            raise exception 'Invalid per-day schedule JSON for settings.key=%', new.key
                using errcode = '23514';
        end if;
    end if;
    return new;
end;
$$;

drop trigger if exists settings_guard_work_hours_by_day on public.settings;
create trigger settings_guard_work_hours_by_day
    before insert or update of key, value on public.settings
    for each row
    execute function public.settings_guard_work_hours_by_day();

revoke all on function public.is_hhmm(text) from public, anon;
revoke all on function public.is_valid_work_hours_by_day(jsonb) from public, anon;
revoke all on function public.build_work_hours_by_day(text, text, text) from public, anon;
grant execute on function public.is_hhmm(text) to authenticated, service_role;
grant execute on function public.is_valid_work_hours_by_day(jsonb) to authenticated, service_role;
grant execute on function public.build_work_hours_by_day(text, text, text) to authenticated, service_role;

insert into public.settings (key, value)
select
    'schedule',
    public.build_work_hours_by_day(
        (select s.value from public.settings s where s.key = 'work_days' limit 1),
        (select s.value from public.settings s where s.key = 'work_start' limit 1),
        (select s.value from public.settings s where s.key = 'work_end' limit 1)
    )::text
on conflict (key) do nothing;

insert into public.settings (key, value)
select
    'professional_' || prof.professional_id || '_schedule',
    public.build_work_hours_by_day(
        (
            select s.value
            from public.settings s
            where s.key = 'professional_' || prof.professional_id || '_work_days'
            limit 1
        ),
        coalesce(
            (
                select s.value
                from public.settings s
                where s.key = 'professional_' || prof.professional_id || '_work_start'
                limit 1
            ),
            (select s.value from public.settings s where s.key = 'work_start' limit 1)
        ),
        coalesce(
            (
                select s.value
                from public.settings s
                where s.key = 'professional_' || prof.professional_id || '_work_end'
                limit 1
            ),
            (select s.value from public.settings s where s.key = 'work_end' limit 1)
        )
    )::text
from (
    select distinct substring(key from '^professional_([0-9]+)_') as professional_id
    from public.settings
    where key ~ '^professional_[0-9]+_(work_start|work_end|work_days)$'
) as prof
where prof.professional_id is not null
on conflict (key) do nothing;

commit;
